statics_url: https://adelnor.criselgeek.com/statics/
development: true
debug: true
cors:
  active: true
  domains: null
timezone: America/Mazatlan
auth:
  hash: VQ!R8?(GV*pAM)vKe^WvxC!$pB681d8u
mailer:
  host: mail.roomyhost.com
  user: dev@chavodigital.com
  password: FlH^9XC$5WW!19KC
  email: dev@chavodigital.com
  port: 465
  smtp_secure: ssl
  smtp_auth: true
  debug: 0
  smtp: true
  sender: Adelnor
recipients:
   contact:
     to:
       email: dev@chavodigital.com
       name: Contacto
     cc:
       email: cristian@migarage.mx
       name: Martha Carrillo
   jobs:
     to:
       email: dev@chavodigital.com
       name: Bolsa de trabajo
     cc:
       email: cristian@migarage.mx
       name: Martha Carrillo
